export const mockData = {
  courses: [
    {
      id: 1,
      name: "Desarrollo Web Full Stack",
      version: "v2.0",
      price: 450,
      status: "active",
      enrollments: 28,
    },
    {
      id: 2,
      name: "Data Science con Python",
      version: "v1.5",
      price: 380,
      status: "active",
      enrollments: 22,
    },
    {
      id: 3,
      name: "Diseño UX/UI",
      version: "v3.0",
      price: 320,
      status: "active",
      enrollments: 35,
    },
    {
      id: 4,
      name: "Marketing Digital",
      version: "v1.0",
      price: 280,
      status: "draft",
      enrollments: 0,
    },
  ],
  enrollments: [
    {
      id: 1,
      student: "Juan Pérez",
      course: "Desarrollo Web",
      payment_status: "paid",
      academic_status: "active",
      amount: 450,
    },
    {
      id: 2,
      student: "María García",
      course: "Data Science",
      payment_status: "pending",
      academic_status: "active",
      amount: 380,
    },
    {
      id: 3,
      student: "Carlos López",
      course: "Diseño UX/UI",
      payment_status: "paid",
      academic_status: "active",
      amount: 320,
    },
    {
      id: 4,
      student: "Ana Martínez",
      course: "Desarrollo Web",
      payment_status: "partial",
      academic_status: "active",
      amount: 450,
    },
  ],
  students: [
    {
      id: 1,
      name: "Juan Pérez",
      email: "juan@example.com",
      courses: 2,
      status: "active",
    },
    {
      id: 2,
      name: "María García",
      email: "maria@example.com",
      courses: 1,
      status: "active",
    },
    {
      id: 3,
      name: "Carlos López",
      email: "carlos@example.com",
      courses: 1,
      status: "active",
    },
    {
      id: 4,
      name: "Ana Martínez",
      email: "ana@example.com",
      courses: 3,
      status: "active",
    },
    {
      id: 5,
      name: "Luis Rodríguez",
      email: "luis@example.com",
      courses: 1,
      status: "inactive",
    },
  ],
  teachers: [
    {
      id: 1,
      name: "Dr. Roberto Sánchez",
      speciality: "Desarrollo Web",
      courses: 3,
      students: 45,
    },
    {
      id: 2,
      name: "Ing. Patricia Díaz",
      speciality: "Data Science",
      courses: 2,
      students: 32,
    },
    {
      id: 3,
      name: "Lic. Miguel Torres",
      speciality: "Diseño",
      courses: 2,
      students: 38,
    },
  ],
  payrollExpenses: [
    {
      id: 1,
      teacher: "Dr. Roberto Sánchez",
      amount: 2500,
      date: "2024-11-01",
      type: "monthly",
    },
    {
      id: 2,
      teacher: "Ing. Patricia Díaz",
      amount: 2200,
      date: "2024-11-01",
      type: "monthly",
    },
    {
      id: 3,
      teacher: "Lic. Miguel Torres",
      amount: 1800,
      date: "2024-11-01",
      type: "monthly",
    },
  ],
  payments: [
    {
      id: 1,
      student: "Juan Pérez",
      amount: 450,
      date: "2024-11-10",
      status: "approved",
    },
    {
      id: 2,
      student: "María García",
      amount: 190,
      date: "2024-11-12",
      status: "pending",
    },
    {
      id: 3,
      student: "Carlos López",
      amount: 320,
      date: "2024-11-08",
      status: "approved",
    },
  ],
  monthlyData: [
    { month: "Jul", ingresos: 12500, egresos: 8500, estudiantes: 65 },
    { month: "Ago", ingresos: 15200, egresos: 9200, estudiantes: 72 },
    { month: "Sep", ingresos: 18900, egresos: 10500, estudiantes: 85 },
    { month: "Oct", ingresos: 21500, egresos: 11200, estudiantes: 92 },
    { month: "Nov", ingresos: 19800, egresos: 10800, estudiantes: 85 },
  ],
  coursesDistribution: [
    { name: "Desarrollo Web", value: 35, students: 35 },
    { name: "Data Science", value: 28, students: 28 },
    { name: "Diseño UX/UI", value: 22, students: 22 },
    { name: "Marketing", value: 15, students: 15 },
  ],
};